//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach01
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗАКАЗЫ
    {
        public int ID { get; set; }
        public string НАИМЕНОВАНИЕ { get; set; }
        public string ДАТА_ОФОРМЛЕНИЯ_ЗАКАЗА { get; set; }
        public string ДАТА_ОТДАЧИ_ЗАКАЗА { get; set; }
        public Nullable<int> СТОИМОСТЬ__РУБ { get; set; }
        public Nullable<int> ПРЕДОПЛАТА__РУБ { get; set; }
        public string ФИО { get; set; }
        public string СЕРИЯ_ПАСПОРТА { get; set; }
        public string НОМЕР_ПАСПОРТА { get; set; }
        public Nullable<int> ID_МАТЕРИАЛ { get; set; }
    
        public virtual МАТЕРИАЛЫ МАТЕРИАЛЫ { get; set; }
    }
}
