//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach01
{
    using System;
    using System.Collections.Generic;
    
    public partial class МАТЕРИАЛЫ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public МАТЕРИАЛЫ()
        {
            this.ЗАКАЗЫ = new HashSet<ЗАКАЗЫ>();
        }
    
        public int ID { get; set; }
        public string НАИМЕНОВАНИЕ { get; set; }
        public string ЦЕНА_ЗА_ГРАММ { get; set; }
        public Nullable<double> ОСТАТОК__ГР { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗАКАЗЫ> ЗАКАЗЫ { get; set; }
    }
}
